### ISSUE TITLE
Command line arguments in Python script

### ISSUE THREAD

**Issue by kotleta2007** [consolethinks/vhs_ripping_scripts#1]
Hey!

Instead of manually parsing command line arguments in your Python script, why not use the `argparse` package? It's part of the standard library.

You can learn more about it [here](https://realpython.com/python-command-line-arguments/#argparse).

**Comment by consolethinks** [comment]
I haven't even contributed the manual way of parsing arguments actually xD. Buuuut, uhhh first I need to figure out a way to have every dependency of that one script listed and a way to install them in a consistent way. Vapoursynth is a bit of a pain in the you know what.

**Comment by consolethinks** [comment]
The QTGMC script has been updated, there's a wrapper shell script around it as it needs vspipe and ffmpeg for it to function as intended. Parameters have been added, closing this issue now :)
